### ISSUE TITLE
Fehler bei SimpleSearching (?)

### ISSUE THREAD

**Issue by ReinhardtJ** [WConen/Notebooks#1]
Beim Erweitern des Programms (im Kontext der aktuellen KI-Veranstaltung) ist mir aufgefallen, dass einerseits der Zustand in einer list `[m,k,b]` gehalten wird, aber in der Funktion `gib_folgezustaende` die Folgezustände in der Form `[k,m,b]` zurückgegeben werden. Das hat bei mir zu Problemen geführt, als ich das Programm so erweitert habe, dass Startzustände mit `k != m` zugelassen werden.

**Comment by WConen** [comment]
Sie meinen vermutlich folgende Stelle:

`return [[k,m,b] for k,m,b in fzustaende 
                if k >= 0 and k <= max_value and m >= 0 and m <= max_value]`

Eine andere Reihenfolge würde keinen Unterschied machen, dort könnte auch x und y statt k und m stehen. Die Reihenfolge wäre erst relevant, wenn sich die max_values  für Missionare und Kannibalen unterscheiden würden, hier geht es ja nur um das Filtern der vorher erzeugten Zustände und das ist völlig symmetrisch für k und m, m und k, Herzchen und Sternchen, Mädchen und Junge...wenn das bei Ihnen zu einem Problem geführt hat, dann, weil sie angenommen haben, der Wert vorne würde am Ende für k stehen, und nicht für m. Was er nicht tut und was auch nirgendwo so steht...

... aber trotzdem ist die Stelle wirklich unschön (weil potentiell verwirrend)! Ändere ich bei Gelegenheit. Danke!
